theme: jekyll-theme-cayman

# Cayman theme settings
# see: https://github.com/pages-themes/cayman
title: [The title of your site]
description: [A short description of your site's purpose]

google_analytics: [UA-97201233-1]
