theme: jekyll-theme-cayman

# Cayman theme settings
# see: https://github.com/pages-themes/cayman
title: [ARI@CH]
description: [Associazione Ricercatrici e Ricercatori Italiani in Svizzera]

google_analytics: [UA-97201233-1]
